@echo off
color 0a
echo ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssoooooooooooooooooooooooooooooooooooooooooooooooooooo+++ooooooo++++++oooooo++echo +ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
echo sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssoooooooooooooooooooooooooooooooooooooooooooooooo++++++++++++++++++++++++++++++++++echo +oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
echo ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssooooooooooooooooooooooooooooooooooooooooooooo+++o++++++++++++++++++++++++++++++++++++o++echo +ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
echo sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssoooooooooooooooooooooooooooooooooooooooooooo+++++++++++++++++++++++++++++++++++++++++++++++echo +ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
echo ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssooooooooooooooooooooooooooooooooooooooooooo+++++++++++++++++++++++++++++++++++++++++++++++++++echo +ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
echo sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssoooooooooooooooooooooooooooooooooooooooooo++++++++++++++++++++++++++++++++++++++++++++++++++++++echo +oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
echo ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssooooooooooooooooooooooooooooooooooooooooo++++++++++++++++++++++++++++++++++++++++++++++++++++++++++echo echo +oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
echo sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssooooooooooooooooooooooooooooooooooooooooo+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++echo +oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
echo ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssoooooooooooooooooooooooooooooooooooooo+o+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++echo +oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
echo ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssoooooooooooooooooooooooooooooooooooooo+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++echo +oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
echo sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssoooooooooooooooooooooooooooooooooooooo+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++echo +ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
echo sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssooooooooooooooooo----..+ooooooooooo+o++++++++++++++++++++.....-+++++++++++++++++++++++++++++++++/.....:+++++++++echo +oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
echo ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssoooooooooooooooooo`     +oooooooooo++++++++++++++++++++++/     .+++++++++++++++++++++++++++++++++:     -++++++++ooecho +ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
echo ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssoooooooooooooooooo`     +oooooooooo++++++++++++++++++++++/     `+++++++++++++++++++++++++++++++++:     -+++++++++echo +oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
echo sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssooooooooooooooooo`     +ooooooooo+++++++++++++++++++++++/     `+++++++++++++++++++++++++++++++++-     -++++++++++echo +ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
echo sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssoooooooo-:/+ooooooo`     +oooooo+/::+++++++++++/-::/++++++/     `++++++//:-:+++++++++++:-::/++++++-     -+++++++//:/echo +oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
echo sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssooooooo:    `.-:/++`     ++/:-.``   :++++++++++.    `.-:://     `//:--``    ://////+++/`    `.-://-     -+/::-``   `+oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
echo ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssooooooo+`          `      ``         `+++++++++:           `      `          `////////+.          `      ``          -oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
echo ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssooooooo+:-.``                     ``.-/++++++++/-..`                      ``.-/////////:-.``                      `.-:+ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
echo ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssooooooooooo++/:-.`          ``.-:/+++++++++++++++++//:-.``          ``.-:://////////////++///:-.`           `..-//++++oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
echo ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssoooooooooooooooo+-          :+oooooo++++++++++++++++++++/.         `:///////////////////++++++++:`         `/+++++++++oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
echo ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssooooooooooooooo+.            -+oooooo++++++++++++++++++:`           `-//////////////////++++++/-`           `/++++++++oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
echo ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssoooooooooooooo/`     `/:`     `/ooo+++++++++++++++++++-      ./-      ./////////////////+++++/.      -/.      -+++++++oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
echo ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssoooooooooooo+-      -+oo+.     `:+o+++++++++++++++++/.     `-+++:`     `://////////////+++++:`     `:+++-      ./+++++++oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
echo ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssooooooooooo+.     `/ooooo+-      .+++++++++++++++++:`     `/+++++/.      -////////////+++++-      ./+++++/`     `/++++oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
echo ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssoooooooooooo/-`  .+oooooooo/`  `-/++++++++++++++++++:.   -++++++++/-   `-///////////+++++++/-`  `:+++++++++-   .:++++++ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
echo sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssoooooooooooooo/:ooooooooooo+-:+ooo+o+++++++++++++++++/-:+++++++++++/.://////////+++++++++++++/-/+++++++++++:-/++++++o+ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
echo sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssoooooooooooooooooooooooooooooooooooo+++++++++++++++++++++++++++++++++++++++/+++++++++++++++++++++++++++++++++++++++oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
echo sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssooooooooooooooooooooooooooooooooooo+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
echo ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssoooooooooooooooooooooooooooooooooo++o++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++o+ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
echo ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssoooooooooooooooooooooooooooooooooooo++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
echo sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssoooooooooooooooooooooooooooooooooooooo++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
echo ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssoooooooooooooooooooooooooooooooooooo+o++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++o+oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
echo ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssooooooooooooooooooooooooooooooooooooo++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
echo sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssooooooooooooooooooooooooooooooooooooooo++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
echo sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssoooooooooooooooooooooooooooooooooooooooo++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
echo ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssoooooooooooooooooooooooooooooooooooooooo+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
echo sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssoooooooooooooooooooooooooooooooooooooooooooo++++++++++++++++++++++++++++++++++++++++++++++++++++o+ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
echo ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssooooooooooooooooooooooooooooooooooooooooooooo++++++++++++++++++++++++++++++++++++++++++++++++ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
echo sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssooooooooooooooooooooooooooooooooooooooooooooooo++++++++++++++++++++++++++++++++++++++++++oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
echo ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssooooooooooooooooooooooooooooooooooooooooooooooooooo+++++++++++++++++++++++++++++++++oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
echo ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssooooooooooooooooooooooooooooooooooooooooooooooooooooo+++++ooo++++++++++++ooo+++++ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
echo sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssoooooooooooooooooooooooooooooooooooooooooooooooooooooooo++++++++++++++++ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
echo ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
echo sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
echo ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo::+oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
echo sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss+...-sssoooooooooooooooooooooooooooo/..oooooooooo/-.....+ooooooooooooooooooooooooooooo``/ooooooo/-.....:ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
echo sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss.`:.`/sssooooooooooooooooooooooooooo/``ooooooooo:`.:/+//oooooo+++ooooooooooo++oooooooo``+ooooooo+/++++.`:sooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
echo ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss+`.s/`.sssso:-......---....:+oooooooo/``oooooooo/``+ooooooooo:.....-/ooooo/-.....:+oooo``+ooooooooooooo-`:ssoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
echo ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss.`/ss``+ssss.`-++++.`.++++.`.oooooooo/``sooooooo-`.osooooooo-`-+++/``/ooo/``/+++:`.oooo``+soooooooooo+-`.ossoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
echo sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss+``sss:`.ssss.`:ssss-`-ssss+` osoooooo/``ssoooooo.`-ssoooooo/``ooooo/``ooo.`-soooo.`:soo``+sooooooooo.`-/osssoooooooosooooooossssssssssssssssssssssssssssssssssssssssssssssssss
echo sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss-`:sso+``+sss.`:ssss-`-ssss+` ossooooo/``ssoooooo.`-ssoooooo:``ooooo+``ooo``/soooo-`-sso``+soooooooo:`/ssssoooooossssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
echo ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss+```....``-sss.`:ssss-`-ssss+` ossooooo/``ssoooooo-`.ssoooooo:``ooooo+``oso``/soooo-`-sso``+ssooooooo:`osssoooooosssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
echo ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss-`-ooooo/``oss.`:ssss-`-ssss+` ossooooo/``ssoooooo/``+ssooooo+``ooooo:`.sso-`-soooo``/sso``+ssoooooooooosssoosssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
echo ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssso``ossssss``:ss.`:ssss-`-ssss+` ossooooo/``ssooooooo:``:///:ooo-`./+/:``+sso+``:++/-`.ssso``:+osoooooo``-ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
echo sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss+::sssssss/::ss:-+ssss/-/sssso--ssssoooo+-:sssooooooo+:-----osso/:----:ossoooo:-----/sssso/---+ssooooo--/ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
echo sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssoooooosssoooooooooooooossssoooooosssoooooooooossssssooooossssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
echo sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssoooooooooooooooooooooooooooooooooooooooooooooooosssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
echo ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssooooooooooooooooooooooooooooooooooooooooooooosssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
echo sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssooooooooooooooooooooooooooooooooooossssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
echo ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
echo ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
echo ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
echo ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
echo ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
echo ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
echo ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
echo ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
pause>nul